name: Publish tagged release

on:
  push:
    tags: ['v[0-9]+.[0-9]+', 'v[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Win32 Executable
          path: binaries\Win32
      - uses: actions/download-artifact@v4
        with:
          name: x64 Executable
          path: binaries\x64
      - name: Publish tested release binaries
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          Move-Item binaries\Win32\pd.exe pd32.exe
          Move-Item binaries\x64\pd.exe pd64.exe
          gh release create $env:RELEASE_VERSION pd32.exe pd64.exe --verify-tag --title $env:RELEASE_VERSION --generate-notes
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
